const customFileHeader = [
	"Do not edit directly — this is auto generated by style-dictionary",
	"Updates are made via ./tokens/*.json",
];

var Color = require("tinycolor2");

module.exports = {
	source: ["./tokens/**/*.json"],
	transform: {
		boxShadowTransformer: {
			type: "value",
			matcher: (token) => token.path.includes("box-shadow"),
			transformer: (token) => token.value,
		},
		hexToHsl: {
			type: "value",
			matcher: (token) =>
				/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/.test(token.value),
			transformer: (token) => {
				return Color(token.value).toHslString();
			},
		},
		pxToRem: {
			type: "value",
			// matcher: token => /\d*\.?\d*px/i.test(token.value) ,
			matcher: (token) =>
				/\d*\.?\d*px/i.test(token.value) && !token.path.includes("box-shadow"),
			transformer: (token) => {
				const floatVal = parseFloat(token.value);

				if (floatVal === 0) {
					return "0";
				}

				return `${floatVal / 16}rem`;
			},
		},
		stripPxUnit: {
			type: "value",
			matcher: (token) =>
				typeof token.value === "string" &&
				token.value.endsWith("px") &&
				token.path.includes("breakpoint"), // only for breakpoints
			transformer: (token) => parseInt(token.value.replace("px", ""), 10),
		},
	},
	platforms: {
		scss: {
			buildPath: "styles/",
			transforms: [
				"attribute/cti",
				"name/cti/kebab",
				"time/seconds",
				"content/icon",
				"size/rem",
				"color/css",
				"boxShadowTransformer",
				"pxToRem",
				"hexToHsl",
			],
			files: [
				{
					destination: "_css-variables.css",
					format: "css/variables",
					options: {
						fileHeader: () => customFileHeader,
						outputReferences: true,
					},
				},
				{
					destination: "_base-variables.scss",
					format: "scss/variables",
					options: {
						fileHeader: () => customFileHeader,
						outputReferences: true,
					},
				},
			],
		},
		js: {
			buildPath: "./styles/",
			transforms: [
				"attribute/cti",
				"name/cti/pascal",
				"size/rem",
				"color/hex",
				"boxShadowTransformer",
				"hexToHsl",
				"stripPxUnit",
			],
			files: [
				{
					destination: "variables.js",
					format: "javascript/es6",
					options: {
						fileHeader: () => customFileHeader,
						outputReferences: true,
					},
				},
			],
		},
	},
};
