function hexToHsl(hex) {
	const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
	if (!result) return hex;
	let r = parseInt(result[1], 16) / 255;
	let g = parseInt(result[2], 16) / 255;
	let b = parseInt(result[3], 16) / 255;
	const max = Math.max(r, g, b);
	const min = Math.min(r, g, b);
	let h = 0;
	let s = 0;
	const l = (max + min) / 2;
	if (max !== min) {
		const d = max - min;
		s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
		if (max === r) h = ((g - b) / d + (g < b ? 6 : 0)) / 6;
		else if (max === g) h = ((b - r) / d + 2) / 6;
		else h = ((r - g) / d + 4) / 6;
	}
	return `hsl(${Math.round(h * 360)}, ${Math.round(s * 100)}%, ${Math.round(l * 100)}%)`;
}

export default {
	source: ["./tokens/**/*.json"],
	hooks: {
		fileHeaders: {
			customHeader: () => [
				"Do not edit directly — this is auto generated by style-dictionary",
				"Updates are made via ./tokens/*.json",
			],
		},
		transforms: {
			boxShadowTransformer: {
				type: "value",
				filter: (token) => token.path.includes("box-shadow"),
				transform: (token) => token.value,
			},
			hexToHsl: {
				type: "value",
				filter: (token) =>
					/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/.test(token.value),
				transform: (token) => hexToHsl(token.value),
			},
			pxToRem: {
				type: "value",
				filter: (token) =>
					/\d*\.?\d*px/i.test(token.value) &&
					!token.path.includes("box-shadow"),
				transform: (token) => {
					const floatVal = parseFloat(token.value);
					if (floatVal === 0) return "0";
					return `${floatVal / 16}rem`;
				},
			},
			stripPxUnit: {
				type: "value",
				filter: (token) =>
					typeof token.value === "string" &&
					token.value.endsWith("px") &&
					token.path.includes("breakpoint"),
				transform: (token) => parseInt(token.value.replace("px", ""), 10),
			},
		},
	},
	platforms: {
		scss: {
			buildPath: "styles/",
			transforms: [
				"name/kebab",
				"time/seconds",
				"html/icon",
				"size/rem",
				"color/css",
				"boxShadowTransformer",
				"pxToRem",
				"hexToHsl",
			],
			files: [
				{
					destination: "_css-variables.css",
					format: "css/variables",
					options: {
						fileHeader: "customHeader",
						outputReferences: true,
					},
				},
				{
					destination: "_base-variables.scss",
					format: "scss/variables",
					options: {
						fileHeader: "customHeader",
						outputReferences: true,
					},
				},
			],
		},
		js: {
			buildPath: "./styles/",
			transforms: [
				"name/pascal",
				"size/rem",
				"color/hex",
				"boxShadowTransformer",
				"hexToHsl",
				"stripPxUnit",
			],
			files: [
				{
					destination: "variables.js",
					format: "javascript/es6",
					options: {
						fileHeader: "customHeader",
						outputReferences: true,
					},
				},
			],
		},
	},
};
